name: Unit tests

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ['3.9.10']

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:    
          python-version: '3.9.10'
      - name: Install ubuntu dependencies
        shell: bash -el {0}
        run: |
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test
            sudo apt-get update
            sudo apt-get install libopenmpi-dev openmpi-bin
      - name: Check MPI version
        shell: bash -el {0}
        run: |
            mpiexec --version
      - name: Check Python version
        shell: bash -el {0}
        run: |
            python --version
    
      - name: Install dependencies
        shell: bash -el {0}
        run: |
           python -m pip install --upgrade pip
           python -m pip install mpi4py
      - name: Install HNN-core
        shell: bash -el {0}
        run: |
          python -m pip install --verbose '.[opt, parallel, test, gui]'

      - name: Lint with flake8
        shell: bash -el {0}
        run: |
          flake8 --count hnn_core

      - name: Test with pytest
        shell: bash -el {0}
        run: |
          python -m pytest ./hnn_core/tests/test_parallel_backends.py  --cov=hnn_core --cov-report=xml

      - name:  Upload coverage to Codecov
        shell: bash -el {0}
        run: |
          bash <(curl -s https://codecov.io/bash) -f ./coverage.xml